import canonicalLaneMathlib.AdmissibleClass
import BoundaryValuesSolutionsEllipticEquationsLemmaCanonicalLaneLean.BoundaryValueProblem
import BoundaryValuesSolutionsEllipticEquationsLemmaCanonicalLaneLean.PotentialTheoryEmbedding
import BoundaryValuesSolutionsEllipticEquationsLemmaCanonicalLaneLean.LayerPotentialEstimates

namespace HautevilleHouse
namespace BoundaryValuesSolutionsEllipticEquationsLemmaCanonicalLaneLean

def ConstrainedBoundaryValueClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_boundary_value_endgame (A : AdmissibleClass) : ConstrainedBoundaryValueClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end BoundaryValuesSolutionsEllipticEquationsLemmaCanonicalLaneLean
end HautevilleHouse